config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  resources :posts, only: [:index, :new, :create]
  resources :replies, only: [:new, :show, :create]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:edit, :update]
  resources :contacts, only: [:index]
  resources :calendars, only: [:show]

  get 'users/my_page' => 'users#show'
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: "users_unsubscribe"
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: "users_withdrawal"

  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'

  get 'homes/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :receive_user, class_name: "User"
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    if @post.user_id != current_user.id
      @favorite = Favorite.create(receive_user_id: current_user.id, post_id: @post.id)
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @post = @favorite.post
    @favorite.destroy
  end

  private

  def favorite_params
    params.require(:favorite).permit(:receive_user_id, :post_id)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(receive_user_id: current_user.id, post_id: post.id) %>
  <%= link_to favorites_path(post_id: post.id), method: :post, remote: true, class:"favorite-btn" do %>
    <i class="far fa-star fa-2x"></i>
  <% end %>
<% else %>
  <%= link_to favorite_path(id: post.favorite.id), method: :delete, remote: true, class:"favorite-btn" do %>
    <i class="fas fa-star fa-2x"></i>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_<%= @post.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { post: @post }) %>");

app/views/favorites/destroy.js.erb
$("#favorite_<%= @post.id %>").html("<%= j(render partial: "favorites/favorite", locals: { post: @post }) %>");