config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  resources :posts, only: [:index, :new, :create]
  resources :replies, only: [:new, :show, :create]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:edit, :update]
  resources :contacts, only: [:index]
  resources :calendars, only: [:show]

  get 'users/my_page' => 'users#show'
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: "users_unsubscribe"
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: "users_withdrawal"

  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'

  get 'homes/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy

  validates :nickname, presence: true, uniqueness: true
  validates :job, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  mount_uploader :profile_image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum place: {
    "---": 0,
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
    沖縄県: 47,
  }

  def not_current_user?(current_user)
    current_user.id != id
  end

  def exists_posts_at_day?(day)
    posts.each.any? do |post|
      post.created_at.to_date === day
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def reject_inactive_user
    @user = User.find_by(nickname: params[:user][:nickname])
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_active
        redirect_to new_user_session_path
      end
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @post = Post.where(user_id: current_user.id).page(params[:user_page]).per(4)
    @user = User.find(current_user.id)
    favorites = Favorite.where(receive_user_id: current_user.id).pluck(:post_id)
    @favorites = Post.where(id: favorites).page(params[:favorite_page]).per(4)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_my_page_path(@user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update!(is_active: false)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :place, :job, :profile_image, :is_active)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="profile-edit">
  <div class="profile-edit__heading">
    <h1 class="profile-edit__title text-center">My Profile Edit</h1>
  </div>
  <% if @user.errors.any? %>
    <div class="error-message">
      <ul class="error-messages">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="profile-form">
    <%= form_with model: @user, url: user_path, local: true do |f| %>

      <div class="form-group row profile-form__form">
        <label class="offset-3 control-label text-left col-md-3 px-0 profile-form__label">プロフィール画像</label>
        <%= f.file_field :profile_image, class: "profile-form__file" %>
      </div>

      <div class="form-group row profile-form__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left profile-form__label">ニックネーム</label>
        <%= f.text_field :nickname , class:"form-control pl-0 col-md-4 profile-form__text" %>
      </div>

      <div class="form-group row profile-form__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left profile-form__label">Eメール</label>
        <%= f.text_field :email , class:"form-control pl-0 col-md-4 profile-form__text" %>
      </div>

      <div class="form-group row profile-form__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left profile-form__label">住んでいる都道府県</label>
        <%= f.select :place , User.places.keys, {}, class:"form-control pl-0 col-md-4 profile-form__select" %>
      </div>

      <div class="form-group row profile-form__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left profile-form__label">仕事</label>
        <%= f.text_field :job , class:"form-control pl-0 col-md-4 profile-form__text" %>
      </div>

      <div class="profile-form__button-group">
        <%= f.submit 'EDIT', class:"profile-form__fuwatto-button--green" %>
        <%= link_to "UNSUBSCRIBE", users_unsubscribe_path(@user.id), class: "profile-form__fuwatto-button--red" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="my-page">
  <div class="my-page__heading">
    <h1 class="my-page__title">My page</h1>
  </div>
  <div class="my-page__profile">
    <div class="my-page__profile-content">
      <%= image_tag @user.profile_image.url, class: "my-page__icon_image", fallback: "no_image.jpg" %>
      <div class="my-page__profile-box">
        <label class="my-page__profile-name">ニックネーム:</label><label class="my-page__profile-item"><%= @user.nickname %></label><br>
        <label class="my-page__profile-place">住まい:</label><label class="my-page__profile-item"><%= @user.place %></label><br>
        <label class="my-page__profile-job">仕事:</label><label class="my-page__profile-item"><%= @user.job %></label>
      </div>
    </div>
    <div class="my-page__btn-box">
      <div class="my-page__edit-btn">
        <%= link_to "EDIT", edit_user_path(@user.id), class: 'btn my-page__btn-shadow' %>
      </div>
      <div class="my-page__calender-btn">
        <%= link_to "Calender", calendar_path(@user.id), class: 'btn my-page__btn-shadow' %>
      </div>
    </div>
  </div>
</div>

<div class="my-content">
  <div class="my-content__post">
    <div class="my-content__post-heading">
      <h2 class="my-content__post-title">My Post List</h2>
    </div>
    <div class="my-content__post-list">
      <% @post.each do |user| %>
        <div class="my-content__post-item">
        <% post_user = User.find_by(id: user.receive_user_id) %>
          <label class="my-content__post-name">Dear&emsp;<%= post_user.nickname %></label>
          <label class="my-content__post-content"><%= user.post_content %></label>
          <label class="my-content__post-time"><%= time_ago_in_words(user.created_at) %></label>
        </div>
      <% end %>
    </div>
    <%= paginate @post, :param_name => 'user_page' %>
  </div>

  <div class="my-content__favorite">
    <div class="my-content__favorite-heading">
      <h2 class="my-content__favorite-title">My Favorite Praise!</h2>
    </div>
    <div class="post-list">
    <% if @favorites.present? %>
      <% @favorites.each do |favorite| %>
        <div class="my-content__post-item">
          <label class="my-content__post-name">From&emsp;<%= favorite.user.nickname %></label>
          <label class="my-content__post-content"><%= favorite.post_content %></label>
          <label class="my-content__post-time"><%= time_ago_in_words(favorite.created_at) %></label>
        </div>
      <% end %>
    <% end %>
    </div>
    <%= paginate @favorites, :param_name => 'favorite_page' %>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="unsubscribe">
  <div class="unsubscribe__heading">
    <h1 class="text-center unsubscribe__title">UNSUBSCRIBE</h1>
  </div>
  <div class="unsubscribe__content">
    <label class="unsubscribe__text">本当に退会しますか？</label>
  </div>
  <div class="unsubscribe__button-group">
    <%= link_to "Continue the habit", users_my_page_path(@user.id), class: 'unsubscribe__fuwatto-button--blue' %>
    <%= link_to "Unsubscribe", users_withdrawal_path(@user.id), method: :patch, class: 'unsubscribe__fuwatto-button--red' %>
  </div>

</div>