config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  resources :posts, only: [:index, :new, :create]
  resources :replies, only: [:new, :show, :create]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:edit, :update]
  resources :contacts, only: [:index]
  resources :calendars, only: [:show]

  get 'users/my_page' => 'users#show'
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: "users_unsubscribe"
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: "users_withdrawal"

  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'

  get 'homes/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => '名前を入力してください' }
  validates :email, :presence => { :message => 'メールアドレスを入力してください' }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => '不正なメールアドレスです' }

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(params[:contact].permit(:name, :email, :message))
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @contact = Contact.new(params[:contact].permit(:name, :email, :message))
    ContactMailer.received_email(@contact).deliver_now

    render :action => 'thanks'
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="confirm container">
  <div class="confirm__heading">
    <h1 class="confirm__title">Confrmation</h1>
  </div>
  <%= form_for @contact, :url => contacts_thanks_path do |f| %>
    <div class="confirm__box">
      <div class="form-group row confirm__from">
        <label class="control-label offset-3 col-md-3 px-0 text-left confirm__label">ニックネーム</label>
        <%= f.hidden_field :name %>
        <label class="pl-0 col-md-4 confirm__label"><%= @contact.name %></label>
      </div>
      <div class="form-group row confirm__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left confirm__label">メールアドレス</label>
        <%= f.hidden_field :email %>
        <label class="pl-0 col-md-4 confirm__label"><%= @contact.email %></label>
      </div>
      <div class="form-group row confirm__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left confirm__label">お問い合わせ内容</label>
        <%= f.hidden_field :message %>
        <label class="pl-0 col-md-4 confirm__text"><%= simple_format(@contact.message) %></label>
      </div>
    </div>
    <div class="confirm__contact-button">
      <%= f.submit 'SUBMIT', :class => 'confirm__fuwatto-button--blue' %>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<div class="contact container">
  <%= form_for @contact, :url => contacts_confirm_path do |f| %>
    <div class="contact__heading">
      <h1 class="contact__title">Contact</h1>
    </div>

    <% if @contact.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <strong>入力内容にエラーがあります</strong>
        <ul>
          <% @contact.errors.each do |attr, msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="contact__box">
      <div class="form-group row contact__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left contact__label">ニックネーム<span class="text-danger">（必須）</span></label>
        <%= f.text_field :name , class:"form-control pl-0 col-md-4 contact__text" %>
      </div>
      <div class="form-group row contact__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left contact__label">メールアドレス<span class="text-danger">（必須）</span></label>
        <%= f.text_field :email , class:"form-control pl-0 col-md-4 contact__text" %>
      </div>
      <div class="form-group row contact__form">
        <label class="control-label offset-3 col-md-3 px-0 text-left contact__label">お問い合わせ内容</label>
        <%= f.text_area :message, class:"form-control pl-0 col-md-4 contact__textarea" %>
      </div>
    </div>
    <div class="contact__contact-button">
      <%= f.submit 'CONFIRM', class: "contact__fuwatto-button--green" %>
    </div>
  <% end %>
</div>

app/views/contacts/thanks.html.erb
<div class="contact-thanks">
  <div class="contact-thanks__heading">
    <h1 class="contact-thanks__message">Thank you for contacting us</h1>
  </div>
</div>