config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  resources :posts, only: [:index, :new, :create]
  resources :replies, only: [:new, :show, :create]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:edit, :update]
  resources :contacts, only: [:index]
  resources :calendars, only: [:show]

  get 'users/my_page' => 'users#show'
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: "users_unsubscribe"
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: "users_withdrawal"

  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'

  get 'homes/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => '名前を入力してください' }
  validates :email, :presence => { :message => 'メールアドレスを入力してください' }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => '不正なメールアドレスです' }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :receive_user, class_name: "User"
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :receive_user, class_name: "User"
  belongs_to :user
  has_one :favorite, dependent: :destroy
  has_many :replies, dependent: :destroy

  validates :post_content, presence: true
  scope :last_month, -> { where(created_at: Time.now.prev_month.beginning_of_month..Time.now.prev_month.end_of_month) }
  scope :current_month, -> { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :post
  belongs_to :receive_user, class_name: "User"

  validates :reply_content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy

  validates :nickname, presence: true, uniqueness: true
  validates :job, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  mount_uploader :profile_image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum place: {
    "---": 0,
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
    沖縄県: 47,
  }

  def not_current_user?(current_user)
    current_user.id != id
  end

  def exists_posts_at_day?(day)
    posts.each.any? do |post|
      post.created_at.to_date === day
    end
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @post_day = current_user.posts.where("created_at >= ?", Date.today).count
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(params[:contact].permit(:name, :email, :message))
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @contact = Contact.new(params[:contact].permit(:name, :email, :message))
    ContactMailer.received_email(@contact).deliver_now

    render :action => 'thanks'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).order(name: :asc).page(params[:page])
    @rankings = User.find(Post.group(:user_id).order('count(user_id) desc').limit(10).pluck(:user_id))
  end

  def new
    @user = User.find(params[:id])
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to users_my_page_path
    else
      @user = User.find(params[:post][:receive_user_id])
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :receive_user_id, :post_content)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @user = User.find(params[:id])
    @post = Post.find(params["post_id"])
    @reply = Reply.new
  end

  def create
    @post = Post.find(params["reply"]["post_id"])
    @post.replies.build(reply_params)
    if @post.save
      redirect_to reply_path(current_user.id)
    else
      @reply = Reply.new
      @user = User.find(params[:reply][:receive_user_id])
      render :new
    end
  end

  def show
    @user = User.find(current_user.id)
    @receives = Post.where(receive_user_id: current_user.id).page(params[:receive_page]).per(4)
    @thanks = Post.where(user_id: current_user.id).page(params[:thanks_page]).per(4)
  end

  private

  def reply_params
    params.require(:reply).permit(:post_id, :receive_user_id, :reply_content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @post = Post.where(user_id: current_user.id).page(params[:user_page]).per(4)
    @user = User.find(current_user.id)
    favorites = Favorite.where(receive_user_id: current_user.id).pluck(:post_id)
    @favorites = Post.where(id: favorites).page(params[:favorite_page]).per(4)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_my_page_path(@user.id)
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update!(is_active: false)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :place, :job, :profile_image, :is_active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PraiseHabit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Julius+Sans+One&family=Prata&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Prata&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Shippori+Mincho:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Italianno&family=Shippori+Mincho:wght@500&family=Tangerine:wght@700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="htmlContainer">
      <header id="page-header">
        <div class="wrapper">
          <div class="logo">
            <a class="logo__main" href="/">PRAISE HABIT</a>
          </div>
          <nav class="main-nav">
            <ul class="main-nav__nav-list">
              <% if user_signed_in? %>
                <li class="main-nav__nav-item">
                  <%=link_to "My Page", users_my_page_path, class: "main-nav__item-second" %>
                </li>
                <li class="main-nav__nav-item">
                  <%=link_to "Post Page", posts_path, class: "main-nav__item-second" %>
                </li>
                <li class="main-nav__nav-item">
                  <%=link_to "Receive Page", reply_path(current_user.id), class: "main-nav__item-second" %>
                </li>
                <li class="main-nav__nav-item">
                  <%=link_to "Contact", contacts_path, class: "main-nav__item-second" %>
                </li>
                <li class="main-nav__nav-item">
                  <%=link_to "Sign Out", destroy_user_session_path, method: :delete, class: "main-nav__item-second" %>
                </li>
              <% else %>
                <li class="main-nav__nav-item">
                  <%=link_to "About", homes_about_path, class: "main-nav__item-second" %>
                </li>
                <li class="main-nav__nav-item">
                  <%=link_to "Contact", contacts_path, class: "main-nav__item-second" %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer>
        <div class="footer">
          <%= audio_tag 'odayakanaakinohi.mp3', id:"bgm" %>
          <button id="btn-play" type="button"><i class="fas fa-volume-off fa-2x"></i></button>
          <script>
            const bgm = document.querySelector("#bgm");
            const btn  = document.querySelector("#btn-play");
            btn.addEventListener("click", ()=>{
              if( ! bgm.paused ){
                btn.innerHTML = '<i class="fas fa-volume-off fa-2x"></i>';
                bgm.pause();
              }
              else{
                btn.innerHTML = '<i class="fas fa-volume-up fa-2x"></i>';
                bgm.play();
              }
            });
             bgm.addEventListener("ended", ()=>{
              bgm.currentTime = 0;
              btn.innerHTML = '<i class="fas fa-volume-off fa-2x"></i>';
            });
          </script>
          <p class="footer__item">Wishing a bright day</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: 'previous' %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: 'next' %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
                <% if current_user.exists_posts_at_day?(day) %>
                  <%= image_tag 'スターの枠アイコン.png', class: 'icon_star' %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>